# Generated by Django 6.0.2 on 2026-02-07 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exercise_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('matching', 'Matching'), ('typing', 'Typing'), ('listening', 'Listening')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises_exercise',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='exercises.exercise')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson')),
            ],
            options={
                'db_table': 'exercises_exerciselesson',
            },
        ),
        migrations.CreateModel(
            name='ListeningExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_english', models.TextField()),
                ('instruction_dari', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/listening/')),
                ('transcript_english', models.TextField(blank=True)),
                ('transcript_dari', models.TextField(blank=True)),
                ('exercise', models.OneToOneField(limit_choices_to={'exercise_type': 'listening'}, on_delete=django.db.models.deletion.CASCADE, related_name='listening', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercises_listeningexercise',
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_english', models.TextField()),
                ('question_dari', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercises.listeningexercise')),
            ],
            options={
                'db_table': 'exercises_listeningquestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_english', models.CharField(max_length=500)),
                ('text_dari', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exercises.listeningquestion')),
            ],
            options={
                'db_table': 'exercises_listeningoption',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_english', models.TextField()),
                ('instruction_dari', models.TextField()),
                ('exercise', models.OneToOneField(limit_choices_to={'exercise_type': 'matching'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercises_matchingexercise',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_english', models.CharField(max_length=500)),
                ('left_dari', models.CharField(blank=True, max_length=500)),
                ('right_english', models.CharField(max_length=500)),
                ('right_dari', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='exercises.matchingexercise')),
            ],
            options={
                'db_table': 'exercises_matchingpair',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_english', models.TextField()),
                ('question_dari', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/exercises/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(limit_choices_to={'exercise_type': 'mcq'}, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercises_mcqquestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_english', models.CharField(max_length=500)),
                ('text_dari', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exercises.mcqquestion')),
            ],
            options={
                'db_table': 'exercises_mcqoption',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TypingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_english', models.TextField()),
                ('instruction_dari', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/exercises/')),
                ('exercise', models.OneToOneField(limit_choices_to={'exercise_type': 'typing'}, on_delete=django.db.models.deletion.CASCADE, related_name='typing', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercises_typingexercise',
            },
        ),
        migrations.CreateModel(
            name='TypingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.TextField()),
                ('sentence_dari', models.TextField()),
                ('correct_answer', models.CharField(max_length=500)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/exercises/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('typing_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='exercises.typingexercise')),
            ],
            options={
                'db_table': 'exercises_typingprompt',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(help_text='Store user answers as JSON')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='exercises.exercise')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='courses.lesson')),
            ],
            options={
                'db_table': 'exercises_userexerciseresponse',
                'ordering': ['-completed_at'],
            },
        ),
    ]
