# Generated by Django 6.0.2 on 2026-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Course description')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level', max_length=20)),
                ('thumbnail', models.ImageField(help_text='Course thumbnail', upload_to='courses/thumbnails/')),
                ('is_paid', models.BooleanField(default=False, help_text='Is this a paid course?')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses_course',
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'courses_courseenrollment',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('content_english', models.TextField(help_text='English content/vocabulary')),
                ('content_dari', models.TextField(help_text='Dari translation/content')),
                ('audio_file', models.FileField(blank=True, help_text='Audio pronunciation file', null=True, upload_to='audio/lessons/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lesson order within course')),
                ('estimated_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses_lessonprogress',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=255)),
                ('dari_word', models.CharField(max_length=255)),
                ('example_english', models.TextField(blank=True)),
                ('example_dari', models.TextField(blank=True)),
                ('pronunciation', models.CharField(blank=True, help_text='IPA pronunciation', max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/vocabulary/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/')),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('other', 'Other')], default='noun', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses_vocabulary',
                'ordering': ['order'],
            },
        ),
    ]
