# Generated by Django 6.0.2 on 2026-02-21 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio pronunciation file (MP3, WAV, OGG, M4A)', null=True, upload_to='audio/lessons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_dari',
            field=models.TextField(blank=True, help_text='Dari translation/content (auto-translated if left empty)'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/vocabulary/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
    ]
