# Generated by Django 6.0.2 on 2026-02-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_audio_file_alter_lesson_content_dari_and_more'),
    ]

    operations = [
    ]
