# Generated by Django 6.0.2 on 2026-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_lesson', 'First Lesson'), ('level_up', 'Level Up'), ('course_complete', 'Course Complete'), ('streak_milestone', 'Streak Milestone'), ('xp_milestone', 'XP Milestone')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_achievement',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/')),
                ('badge_type', models.CharField(choices=[('streak', 'Streak'), ('achievement', 'Achievement'), ('milestone', 'Milestone'), ('special', 'Special Event')], default='achievement', max_length=20)),
                ('requirement', models.CharField(help_text='Requirement for earning badge', max_length=255)),
                ('requirement_value', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_badge',
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('complete_lesson', 'Complete 1 Lesson'), ('complete_exercise', 'Complete 3 Exercises'), ('daily_streak', 'Keep Daily Streak'), ('community_post', 'Make Community Post')], max_length=30)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamification_dailychallenge',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('exercises_completed', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'gamification_leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_xp', models.PositiveIntegerField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tiers/')),
                ('perks', models.JSONField(blank=True, default=dict, help_text='Perks for this tier')),
            ],
            options={
                'db_table': 'gamification_tier',
                'ordering': ['min_xp'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_userbadge',
            },
        ),
        migrations.CreateModel(
            name='UserDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('target', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'gamification_userdailychallenge',
            },
        ),
    ]
