# Generated by Django 6.0.2 on 2026-02-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['-created_at']},
        ),
    ]
