# Generated by Django 6.0.2 on 2026-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=255, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('score', models.PositiveIntegerField(default=100, help_text='Final course score')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'certificates_certificate',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template_html', models.TextField(help_text='HTML template with {user_name}, {course_title}, {date}, etc.')),
                ('custom_css', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'certificates_certificatetemplate',
            },
        ),
    ]
